// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	http "net/http"

	rest "k8s.io/client-go/rest"
)

type TrainerV1alpha1Interface interface {
	RESTClient() rest.Interface
	ClusterTrainingRuntimesGetter
	TrainJobsGetter
	TrainingRuntimesGetter
}

// TrainerV1alpha1Client is used to interact with features provided by the trainer.kubeflow.org group.
type TrainerV1alpha1Client struct {
	restClient rest.Interface
}

func (c *TrainerV1alpha1Client) ClusterTrainingRuntimes() ClusterTrainingRuntimeInterface {
	_ = "STUB: not implemented"
	return *new(ClusterTrainingRuntimeInterface)
}

func (c *TrainerV1alpha1Client) TrainJobs(namespace string) TrainJobInterface {
	_ = "STUB: not implemented"
	return *new(TrainJobInterface)
}

func (c *TrainerV1alpha1Client) TrainingRuntimes(namespace string) TrainingRuntimeInterface {
	_ = "STUB: not implemented"
	return *new(TrainingRuntimeInterface)
}

// NewForConfig creates a new TrainerV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*TrainerV1alpha1Client, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewForConfigAndClient creates a new TrainerV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*TrainerV1alpha1Client, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewForConfigOrDie creates a new TrainerV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *TrainerV1alpha1Client {
	_ = "STUB: not implemented"
	return nil
}

// New creates a new TrainerV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *TrainerV1alpha1Client { _ = "STUB: not implemented"; return nil }

func setConfigDefaults(config *rest.Config) { _ = "STUB: not implemented"; return }

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *TrainerV1alpha1Client) RESTClient() rest.Interface {
	_ = "STUB: not implemented"
	return *new(rest.Interface)
}
