// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	context "context"
	reflect "reflect"
	sync "sync"
	time "time"

	versioned "github.com/kubeflow/trainer/v2/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kubeflow/trainer/v2/pkg/client/informers/externalversions/internalinterfaces"
	trainer "github.com/kubeflow/trainer/v2/pkg/client/informers/externalversions/trainer"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// SharedInformerOption defines the functional option type for SharedInformerFactory.
type SharedInformerOption func(*sharedInformerFactory) *sharedInformerFactory

type sharedInformerFactory struct {
	client           versioned.Interface
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	lock             sync.Mutex
	defaultResync    time.Duration
	customResync     map[reflect.Type]time.Duration
	transform        cache.TransformFunc
	informerName     *cache.InformerName

	informers map[reflect.Type]cache.SharedIndexInformer
	// startedInformers is used for tracking which informers have been started.
	// This allows Start() to be called multiple times safely.
	startedInformers map[reflect.Type]bool
	// wg tracks how many goroutines were started.
	wg sync.WaitGroup
	// shuttingDown is true when Shutdown has been called. It may still be running
	// because it needs to wait for goroutines.
	shuttingDown bool
}

// WithCustomResyncConfig sets a custom resync period for the specified informer types.
func WithCustomResyncConfig(resyncConfig map[v1.Object]time.Duration) SharedInformerOption {
	_ = "STUB: not implemented"
	return *new(SharedInformerOption)
}

// WithTweakListOptions sets a custom filter on all listers of the configured SharedInformerFactory.
func WithTweakListOptions(tweakListOptions internalinterfaces.TweakListOptionsFunc) SharedInformerOption {
	_ = "STUB: not implemented"
	return *new(SharedInformerOption)
}

// WithNamespace limits the SharedInformerFactory to the specified namespace.
func WithNamespace(namespace string) SharedInformerOption {
	_ = "STUB: not implemented"
	return *new(SharedInformerOption)
}

// WithTransform sets a transform on all informers.
func WithTransform(transform cache.TransformFunc) SharedInformerOption {
	_ = "STUB: not implemented"
	return *new(SharedInformerOption)
}

// WithInformerName sets the InformerName for informer identity used in metrics.
// The InformerName must be created via cache.NewInformerName() at startup,
// which validates global uniqueness. Each informer type will register its
// GVR under this name.
func WithInformerName(informerName *cache.InformerName) SharedInformerOption {
	_ = "STUB: not implemented"
	return *new(SharedInformerOption)
}

func (f *sharedInformerFactory) InformerName() *cache.InformerName {
	_ = "STUB: not implemented"
	return nil

	// NewSharedInformerFactory constructs a new instance of sharedInformerFactory for all namespaces.
}

func NewSharedInformerFactory(client versioned.Interface, defaultResync time.Duration) SharedInformerFactory {
	_ = "STUB: not implemented"
	return *new(SharedInformerFactory)
}

// NewFilteredSharedInformerFactory constructs a new instance of sharedInformerFactory.
// Listers obtained via this SharedInformerFactory will be subject to the same filters
// as specified here.
//
// Deprecated: Please use NewSharedInformerFactoryWithOptions instead
func NewFilteredSharedInformerFactory(client versioned.Interface, defaultResync time.Duration, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) SharedInformerFactory {
	_ = "STUB: not implemented"
	return *new(SharedInformerFactory)
}

// NewSharedInformerFactoryWithOptions constructs a new instance of a SharedInformerFactory with additional options.
func NewSharedInformerFactoryWithOptions(client versioned.Interface, defaultResync time.Duration, options ...SharedInformerOption) SharedInformerFactory {
	_ = "STUB: not implemented"
	return *new(SharedInformerFactory)
}

// Apply all options

func (f *sharedInformerFactory) Start(stopCh <-chan struct{}) { _ = "STUB: not implemented"; return }

func (f *sharedInformerFactory) StartWithContext(ctx context.Context) {
	_ = "STUB: not implemented"
	return
}

func (f *sharedInformerFactory) Shutdown() { _ = "STUB: not implemented"; return }

// Will return immediately if there is nothing to wait for.

func (f *sharedInformerFactory) WaitForCacheSync(stopCh <-chan struct{}) map[reflect.Type]bool {
	_ = "STUB: not implemented"
	return nil
}

func (f *sharedInformerFactory) WaitForCacheSyncWithContext(ctx context.Context) cache.SyncResult {
	_ = "STUB: not implemented"
	return *new(cache.SyncResult)
}

// Wait for informers to sync, without polling.

/* no logging */

// context.Cause is more informative than ctx.Err().
// This must be non-nil, otherwise WaitFor wouldn't have stopped
// prematurely.

// InformerFor returns the SharedIndexInformer for obj using an internal
// client.
func (f *sharedInformerFactory) InformerFor(obj runtime.Object, newFunc internalinterfaces.NewInformerFunc) cache.SharedIndexInformer {
	_ = "STUB: not implemented"
	return *new(cache.SharedIndexInformer)
}

// SharedInformerFactory provides shared informers for resources in all known
// API group versions.
//
// It is typically used like this:
//
//	ctx, cancel := context.WithCancel(context.Background())
//	defer cancel()
//	factory := NewSharedInformerFactory(client, resyncPeriod)
//	defer factory.WaitForStop()    // Returns immediately if nothing was started.
//	genericInformer := factory.ForResource(resource)
//	typedInformer := factory.SomeAPIGroup().V1().SomeType()
//	handle, err := typeInformer.Informer().AddEventHandler(...)
//	if err != nil {
//	    return fmt.Errorf("register event handler: %v", err)
//	}
//	defer typeInformer.Informer().RemoveEventHandler(handle) // Avoids leaking goroutines.
//	factory.StartWithContext(ctx)                            // Start processing these informers.
//	synced := factory.WaitForCacheSyncWithContext(ctx)
//	if err := synced.AsError(); err != nil {
//	    return err
//	}
//	for v := range synced {
//	    // Only if desired log some information similar to this.
//	    fmt.Fprintf(os.Stdout, "cache synced: %s", v)
//	}
//
//	// Also make sure that all of the initial cache events have been delivered.
//	if !WaitFor(ctx, "event handler sync", handle.HasSyncedChecker()) {
//	    // Must have failed because of context.
//	    return fmt.Errorf("sync event handler: %w", context.Cause(ctx))
//	}
//
//	// Creating informers can also be created after Start, but then
//	// Start must be called again:
//	anotherGenericInformer := factory.ForResource(resource)
//	factory.StartWithContext(ctx)
type SharedInformerFactory interface {
	internalinterfaces.SharedInformerFactory

	// Start initializes all requested informers. They are handled in goroutines
	// which run until the stop channel gets closed.
	// Warning: Start does not block. When run in a go-routine, it will race with a later WaitForCacheSync.
	//
	// Contextual logging: StartWithContext should be used instead of Start in code which supports contextual logging.
	Start(stopCh <-chan struct{})

	// StartWithContext initializes all requested informers. They are handled in goroutines
	// which run until the context gets canceled.
	// Warning: StartWithContext does not block. When run in a go-routine, it will race with a later WaitForCacheSync.
	StartWithContext(ctx context.Context)

	// Shutdown marks a factory as shutting down. At that point no new
	// informers can be started anymore and Start will return without
	// doing anything.
	//
	// In addition, Shutdown blocks until all goroutines have terminated. For that
	// to happen, the close channel(s) that they were started with must be closed,
	// either before Shutdown gets called or while it is waiting.
	//
	// Shutdown may be called multiple times, even concurrently. All such calls will
	// block until all goroutines have terminated.
	Shutdown()

	// WaitForCacheSync blocks until all started informers' caches were synced
	// or the stop channel gets closed.
	//
	// Contextual logging: WaitForCacheSync should be used instead of WaitForCacheSync in code which supports contextual logging. It also returns a more useful result.
	WaitForCacheSync(stopCh <-chan struct{}) map[reflect.Type]bool

	// WaitForCacheSyncWithContext blocks until all started informers' caches were synced
	// or the context gets canceled.
	WaitForCacheSyncWithContext(ctx context.Context) cache.SyncResult

	// ForResource gives generic access to a shared informer of the matching type.
	ForResource(resource schema.GroupVersionResource) (GenericInformer, error)

	// InformerFor returns the SharedIndexInformer for obj using an internal
	// client.
	InformerFor(obj runtime.Object, newFunc internalinterfaces.NewInformerFunc) cache.SharedIndexInformer

	Trainer() trainer.Interface
}

func (f *sharedInformerFactory) Trainer() trainer.Interface {
	_ = "STUB: not implemented"
	return *new(trainer.Interface)
}
