// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
	v1alpha2 "sigs.k8s.io/jobset/client-go/applyconfiguration/jobset/v1alpha2"
)

// JobSetTemplateSpecApplyConfiguration represents a declarative configuration of the JobSetTemplateSpec type for use
// with apply.
//
// JobSetTemplateSpec represents a template of the desired JobSet.
type JobSetTemplateSpecApplyConfiguration struct {
	// metadata for custom JobSet's labels and annotations.
	// JobSet name and namespace is equal to the TrainJob's name and namespace.
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	// spec of the desired JobSet which will be created from TrainJob.
	Spec *v1alpha2.JobSetSpecApplyConfiguration `json:"spec,omitempty"`
}

// JobSetTemplateSpecApplyConfiguration constructs a declarative configuration of the JobSetTemplateSpec type for use with
// apply.
func JobSetTemplateSpec() *JobSetTemplateSpecApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *JobSetTemplateSpecApplyConfiguration) WithName(value string) *JobSetTemplateSpecApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *JobSetTemplateSpecApplyConfiguration) WithGenerateName(value string) *JobSetTemplateSpecApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *JobSetTemplateSpecApplyConfiguration) WithNamespace(value string) *JobSetTemplateSpecApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *JobSetTemplateSpecApplyConfiguration) WithUID(value types.UID) *JobSetTemplateSpecApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *JobSetTemplateSpecApplyConfiguration) WithResourceVersion(value string) *JobSetTemplateSpecApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *JobSetTemplateSpecApplyConfiguration) WithGeneration(value int64) *JobSetTemplateSpecApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *JobSetTemplateSpecApplyConfiguration) WithCreationTimestamp(value metav1.Time) *JobSetTemplateSpecApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *JobSetTemplateSpecApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *JobSetTemplateSpecApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *JobSetTemplateSpecApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *JobSetTemplateSpecApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *JobSetTemplateSpecApplyConfiguration) WithLabels(entries map[string]string) *JobSetTemplateSpecApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *JobSetTemplateSpecApplyConfiguration) WithAnnotations(entries map[string]string) *JobSetTemplateSpecApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *JobSetTemplateSpecApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *JobSetTemplateSpecApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *JobSetTemplateSpecApplyConfiguration) WithFinalizers(values ...string) *JobSetTemplateSpecApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

func (b *JobSetTemplateSpecApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	_ = "STUB: not implemented"
	return
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *JobSetTemplateSpecApplyConfiguration) WithSpec(value *v1alpha2.JobSetSpecApplyConfiguration) *JobSetTemplateSpecApplyConfiguration {
	_ = "STUB: not implemented"
	return nil

	// GetName retrieves the value of the Name field in the declarative configuration.
}

func (b *JobSetTemplateSpecApplyConfiguration) GetName() *string {
	_ = "STUB: not implemented"
	return nil
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *JobSetTemplateSpecApplyConfiguration) GetNamespace() *string {
	_ = "STUB: not implemented"
	return nil
}
