// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/client-go/applyconfigurations/core/v1"
)

// PodSpecPatchApplyConfiguration represents a declarative configuration of the PodSpecPatch type for use
// with apply.
//
// PodSpecPatch contains the Pod spec fields that managers are permitted to patch.
type PodSpecPatchApplyConfiguration struct {
	// serviceAccountName patches the service account for the Pods in the target job templates.
	ServiceAccountName *string `json:"serviceAccountName,omitempty"`
	// volumes patches the Pod's volumes.
	Volumes []v1.VolumeApplyConfiguration `json:"volumes,omitempty"`
	// initContainers patches the init containers in the target job templates.
	InitContainers []ContainerPatchApplyConfiguration `json:"initContainers,omitempty"`
	// containers patches specific containers in the target job templates.
	Containers []ContainerPatchApplyConfiguration `json:"containers,omitempty"`
	// imagePullSecrets patches the image pull secrets for the Pods in the target job templates.
	ImagePullSecrets []corev1.LocalObjectReference `json:"imagePullSecrets,omitempty"`
	// securityContext patches the Pod's security context.
	// More info: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
	SecurityContext *corev1.PodSecurityContext `json:"securityContext,omitempty"`
	// nodeSelector patches the node selector to place Pods on specific nodes.
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
	// affinity patches the Pod's scheduling affinity.
	Affinity *corev1.Affinity `json:"affinity,omitempty"`
	// tolerations patches the Pod's tolerations.
	Tolerations []v1.TolerationApplyConfiguration `json:"tolerations,omitempty"`
	// schedulingGates patches the scheduling gates for the Pods in the target job templates.
	// More info: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-scheduling-readiness/
	SchedulingGates []corev1.PodSchedulingGate `json:"schedulingGates,omitempty"`
}

// PodSpecPatchApplyConfiguration constructs a declarative configuration of the PodSpecPatch type for use with
// apply.
func PodSpecPatch() *PodSpecPatchApplyConfiguration { _ = "STUB: not implemented"; return nil }

// WithServiceAccountName sets the ServiceAccountName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccountName field is set to the value of the last call.
func (b *PodSpecPatchApplyConfiguration) WithServiceAccountName(value string) *PodSpecPatchApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithVolumes adds the given value to the Volumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Volumes field.
func (b *PodSpecPatchApplyConfiguration) WithVolumes(values ...*v1.VolumeApplyConfiguration) *PodSpecPatchApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithInitContainers adds the given value to the InitContainers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the InitContainers field.
func (b *PodSpecPatchApplyConfiguration) WithInitContainers(values ...*ContainerPatchApplyConfiguration) *PodSpecPatchApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithContainers adds the given value to the Containers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Containers field.
func (b *PodSpecPatchApplyConfiguration) WithContainers(values ...*ContainerPatchApplyConfiguration) *PodSpecPatchApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *PodSpecPatchApplyConfiguration) WithImagePullSecrets(values ...corev1.LocalObjectReference) *PodSpecPatchApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithSecurityContext sets the SecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityContext field is set to the value of the last call.
func (b *PodSpecPatchApplyConfiguration) WithSecurityContext(value corev1.PodSecurityContext) *PodSpecPatchApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *PodSpecPatchApplyConfiguration) WithNodeSelector(entries map[string]string) *PodSpecPatchApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *PodSpecPatchApplyConfiguration) WithAffinity(value corev1.Affinity) *PodSpecPatchApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *PodSpecPatchApplyConfiguration) WithTolerations(values ...*v1.TolerationApplyConfiguration) *PodSpecPatchApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithSchedulingGates adds the given value to the SchedulingGates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SchedulingGates field.
func (b *PodSpecPatchApplyConfiguration) WithSchedulingGates(values ...corev1.PodSchedulingGate) *PodSpecPatchApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}
