// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// TrainingRuntimeApplyConfiguration represents a declarative configuration of the TrainingRuntime type for use
// with apply.
//
// TrainingRuntime represents a training runtime which can be referenced as part of
// `runtimeRef` API in TrainJob. This resource is a namespaced-scoped and can be referenced
// by TrainJob that created in the *same* namespace as the TrainingRuntime.
type TrainingRuntimeApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration `json:",inline"`
	// metadata of the TrainingRuntime.
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	// spec of the TrainingRuntime.
	Spec *TrainingRuntimeSpecApplyConfiguration `json:"spec,omitempty"`
}

// TrainingRuntime constructs a declarative configuration of the TrainingRuntime type for use with
// apply.
func TrainingRuntime(name, namespace string) *TrainingRuntimeApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

func (b TrainingRuntimeApplyConfiguration) IsApplyConfiguration() {
	_ = "STUB: not implemented"

	// WithKind sets the Kind field in the declarative configuration to the given value
	// and returns the receiver, so that objects can be built by chaining "With" function invocations.
	// If called multiple times, the Kind field is set to the value of the last call.
	return
}

func (b *TrainingRuntimeApplyConfiguration) WithKind(value string) *TrainingRuntimeApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *TrainingRuntimeApplyConfiguration) WithAPIVersion(value string) *TrainingRuntimeApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *TrainingRuntimeApplyConfiguration) WithName(value string) *TrainingRuntimeApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *TrainingRuntimeApplyConfiguration) WithGenerateName(value string) *TrainingRuntimeApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *TrainingRuntimeApplyConfiguration) WithNamespace(value string) *TrainingRuntimeApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *TrainingRuntimeApplyConfiguration) WithUID(value types.UID) *TrainingRuntimeApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *TrainingRuntimeApplyConfiguration) WithResourceVersion(value string) *TrainingRuntimeApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *TrainingRuntimeApplyConfiguration) WithGeneration(value int64) *TrainingRuntimeApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *TrainingRuntimeApplyConfiguration) WithCreationTimestamp(value metav1.Time) *TrainingRuntimeApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *TrainingRuntimeApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *TrainingRuntimeApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *TrainingRuntimeApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *TrainingRuntimeApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *TrainingRuntimeApplyConfiguration) WithLabels(entries map[string]string) *TrainingRuntimeApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *TrainingRuntimeApplyConfiguration) WithAnnotations(entries map[string]string) *TrainingRuntimeApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *TrainingRuntimeApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *TrainingRuntimeApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *TrainingRuntimeApplyConfiguration) WithFinalizers(values ...string) *TrainingRuntimeApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

func (b *TrainingRuntimeApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	_ = "STUB: not implemented"
	return
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *TrainingRuntimeApplyConfiguration) WithSpec(value *TrainingRuntimeSpecApplyConfiguration) *TrainingRuntimeApplyConfiguration {
	_ = "STUB: not implemented"
	return nil

	// GetKind retrieves the value of the Kind field in the declarative configuration.
}

func (b *TrainingRuntimeApplyConfiguration) GetKind() *string {
	_ = "STUB: not implemented"
	return nil
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *TrainingRuntimeApplyConfiguration) GetAPIVersion() *string {
	_ = "STUB: not implemented"
	return nil
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *TrainingRuntimeApplyConfiguration) GetName() *string {
	_ = "STUB: not implemented"
	return nil
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *TrainingRuntimeApplyConfiguration) GetNamespace() *string {
	_ = "STUB: not implemented"
	return nil
}
