// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// TrainJobApplyConfiguration represents a declarative configuration of the TrainJob type for use
// with apply.
//
// TrainJob represents configuration of a training job.
type TrainJobApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration `json:",inline"`
	// metadata of the TrainJob.
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	// spec of the TrainJob.
	Spec *TrainJobSpecApplyConfiguration `json:"spec,omitempty"`
	// status of TrainJob.
	Status *TrainJobStatusApplyConfiguration `json:"status,omitempty"`
}

// TrainJob constructs a declarative configuration of the TrainJob type for use with
// apply.
func TrainJob(name, namespace string) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

func (b TrainJobApplyConfiguration) IsApplyConfiguration() {
	_ = "STUB: not implemented"

	// WithKind sets the Kind field in the declarative configuration to the given value
	// and returns the receiver, so that objects can be built by chaining "With" function invocations.
	// If called multiple times, the Kind field is set to the value of the last call.
	return
}

func (b *TrainJobApplyConfiguration) WithKind(value string) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *TrainJobApplyConfiguration) WithAPIVersion(value string) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *TrainJobApplyConfiguration) WithName(value string) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *TrainJobApplyConfiguration) WithGenerateName(value string) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *TrainJobApplyConfiguration) WithNamespace(value string) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *TrainJobApplyConfiguration) WithUID(value types.UID) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *TrainJobApplyConfiguration) WithResourceVersion(value string) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *TrainJobApplyConfiguration) WithGeneration(value int64) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *TrainJobApplyConfiguration) WithCreationTimestamp(value metav1.Time) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *TrainJobApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *TrainJobApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *TrainJobApplyConfiguration) WithLabels(entries map[string]string) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *TrainJobApplyConfiguration) WithAnnotations(entries map[string]string) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *TrainJobApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *TrainJobApplyConfiguration) WithFinalizers(values ...string) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil
}

func (b *TrainJobApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	_ = "STUB: not implemented"
	return
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *TrainJobApplyConfiguration) WithSpec(value *TrainJobSpecApplyConfiguration) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil

	// WithStatus sets the Status field in the declarative configuration to the given value
	// and returns the receiver, so that objects can be built by chaining "With" function invocations.
	// If called multiple times, the Status field is set to the value of the last call.
}

func (b *TrainJobApplyConfiguration) WithStatus(value *TrainJobStatusApplyConfiguration) *TrainJobApplyConfiguration {
	_ = "STUB: not implemented"
	return nil

	// GetKind retrieves the value of the Kind field in the declarative configuration.
}

func (b *TrainJobApplyConfiguration) GetKind() *string { _ = "STUB: not implemented"; return nil }

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *TrainJobApplyConfiguration) GetAPIVersion() *string { _ = "STUB: not implemented"; return nil }

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *TrainJobApplyConfiguration) GetName() *string { _ = "STUB: not implemented"; return nil }

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *TrainJobApplyConfiguration) GetNamespace() *string { _ = "STUB: not implemented"; return nil }
