//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTrainingRuntime) DeepCopyInto(out *ClusterTrainingRuntime) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTrainingRuntime.
func (in *ClusterTrainingRuntime) DeepCopy() *ClusterTrainingRuntime {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTrainingRuntime) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTrainingRuntimeList) DeepCopyInto(out *ClusterTrainingRuntimeList) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTrainingRuntimeList.
func (in *ClusterTrainingRuntimeList) DeepCopy() *ClusterTrainingRuntimeList {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTrainingRuntimeList) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerPatch) DeepCopyInto(out *ContainerPatch) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerPatch.
func (in *ContainerPatch) DeepCopy() *ContainerPatch { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoschedulingPodGroupPolicySource) DeepCopyInto(out *CoschedulingPodGroupPolicySource) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoschedulingPodGroupPolicySource.
func (in *CoschedulingPodGroupPolicySource) DeepCopy() *CoschedulingPodGroupPolicySource {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetInitializer) DeepCopyInto(out *DatasetInitializer) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetInitializer.
func (in *DatasetInitializer) DeepCopy() *DatasetInitializer { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxMLPolicySource) DeepCopyInto(out *FluxMLPolicySource) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxMLPolicySource.
func (in *FluxMLPolicySource) DeepCopy() *FluxMLPolicySource { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Initializer) DeepCopyInto(out *Initializer) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Initializer.
func (in *Initializer) DeepCopy() *Initializer { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JAXMLPolicySource) DeepCopyInto(out *JAXMLPolicySource) {
	_ = "STUB: not implemented"
	return

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JAXMLPolicySource.
}

func (in *JAXMLPolicySource) DeepCopy() *JAXMLPolicySource { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobSetSpecPatch) DeepCopyInto(out *JobSetSpecPatch) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobSetSpecPatch.
func (in *JobSetSpecPatch) DeepCopy() *JobSetSpecPatch { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobSetTemplatePatch) DeepCopyInto(out *JobSetTemplatePatch) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobSetTemplatePatch.
func (in *JobSetTemplatePatch) DeepCopy() *JobSetTemplatePatch {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobSetTemplateSpec) DeepCopyInto(out *JobSetTemplateSpec) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobSetTemplateSpec.
func (in *JobSetTemplateSpec) DeepCopy() *JobSetTemplateSpec { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobSpecPatch) DeepCopyInto(out *JobSpecPatch) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobSpecPatch.
func (in *JobSpecPatch) DeepCopy() *JobSpecPatch { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobStatus) DeepCopyInto(out *JobStatus) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobStatus.
func (in *JobStatus) DeepCopy() *JobStatus { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobTemplatePatch) DeepCopyInto(out *JobTemplatePatch) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobTemplatePatch.
func (in *JobTemplatePatch) DeepCopy() *JobTemplatePatch { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLPolicy) DeepCopyInto(out *MLPolicy) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLPolicy.
func (in *MLPolicy) DeepCopy() *MLPolicy { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLPolicySource) DeepCopyInto(out *MLPolicySource) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLPolicySource.
func (in *MLPolicySource) DeepCopy() *MLPolicySource { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MPIMLPolicySource) DeepCopyInto(out *MPIMLPolicySource) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MPIMLPolicySource.
func (in *MPIMLPolicySource) DeepCopy() *MPIMLPolicySource { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Metric) DeepCopyInto(out *Metric) {
	_ = "STUB: not implemented"

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metric.
	return
}

func (in *Metric) DeepCopy() *Metric { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelInitializer) DeepCopyInto(out *ModelInitializer) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelInitializer.
func (in *ModelInitializer) DeepCopy() *ModelInitializer { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupPolicy) DeepCopyInto(out *PodGroupPolicy) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupPolicy.
func (in *PodGroupPolicy) DeepCopy() *PodGroupPolicy { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodGroupPolicySource) DeepCopyInto(out *PodGroupPolicySource) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodGroupPolicySource.
func (in *PodGroupPolicySource) DeepCopy() *PodGroupPolicySource {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSpecPatch) DeepCopyInto(out *PodSpecPatch) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSpecPatch.
func (in *PodSpecPatch) DeepCopy() *PodSpecPatch { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodTemplatePatch) DeepCopyInto(out *PodTemplatePatch) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodTemplatePatch.
func (in *PodTemplatePatch) DeepCopy() *PodTemplatePatch { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicatedJobPatch) DeepCopyInto(out *ReplicatedJobPatch) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicatedJobPatch.
func (in *ReplicatedJobPatch) DeepCopy() *ReplicatedJobPatch { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimePatch) DeepCopyInto(out *RuntimePatch) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimePatch.
func (in *RuntimePatch) DeepCopy() *RuntimePatch { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeRef) DeepCopyInto(out *RuntimeRef) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeRef.
func (in *RuntimeRef) DeepCopy() *RuntimeRef { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TorchMLPolicySource) DeepCopyInto(out *TorchMLPolicySource) {
	_ = "STUB: not implemented"
	return

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TorchMLPolicySource.
}

func (in *TorchMLPolicySource) DeepCopy() *TorchMLPolicySource {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainJob) DeepCopyInto(out *TrainJob) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainJob.
func (in *TrainJob) DeepCopy() *TrainJob { _ = "STUB: not implemented"; return nil }

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrainJob) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainJobList) DeepCopyInto(out *TrainJobList) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainJobList.
func (in *TrainJobList) DeepCopy() *TrainJobList { _ = "STUB: not implemented"; return nil }

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrainJobList) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainJobSpec) DeepCopyInto(out *TrainJobSpec) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainJobSpec.
func (in *TrainJobSpec) DeepCopy() *TrainJobSpec { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainJobStatus) DeepCopyInto(out *TrainJobStatus) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainJobStatus.
func (in *TrainJobStatus) DeepCopy() *TrainJobStatus { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Trainer) DeepCopyInto(out *Trainer) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Trainer.
func (in *Trainer) DeepCopy() *Trainer { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainerStatus) DeepCopyInto(out *TrainerStatus) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainerStatus.
func (in *TrainerStatus) DeepCopy() *TrainerStatus { _ = "STUB: not implemented"; return nil }

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingRuntime) DeepCopyInto(out *TrainingRuntime) { _ = "STUB: not implemented"; return }

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingRuntime.
func (in *TrainingRuntime) DeepCopy() *TrainingRuntime { _ = "STUB: not implemented"; return nil }

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrainingRuntime) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingRuntimeList) DeepCopyInto(out *TrainingRuntimeList) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingRuntimeList.
func (in *TrainingRuntimeList) DeepCopy() *TrainingRuntimeList {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrainingRuntimeList) DeepCopyObject() runtime.Object {
	_ = "STUB: not implemented"
	return *new(runtime.Object)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingRuntimeSpec) DeepCopyInto(out *TrainingRuntimeSpec) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingRuntimeSpec.
func (in *TrainingRuntimeSpec) DeepCopy() *TrainingRuntimeSpec {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingRuntimeSpecPatch) DeepCopyInto(out *TrainingRuntimeSpecPatch) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingRuntimeSpecPatch.
func (in *TrainingRuntimeSpecPatch) DeepCopy() *TrainingRuntimeSpecPatch {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateTrainJobStatusRequest) DeepCopyInto(out *UpdateTrainJobStatusRequest) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateTrainJobStatusRequest.
func (in *UpdateTrainJobStatusRequest) DeepCopy() *UpdateTrainJobStatusRequest {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolcanoPodGroupPolicySource) DeepCopyInto(out *VolcanoPodGroupPolicySource) {
	_ = "STUB: not implemented"
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolcanoPodGroupPolicySource.
func (in *VolcanoPodGroupPolicySource) DeepCopy() *VolcanoPodGroupPolicySource {
	_ = "STUB: not implemented"
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XGBoostMLPolicySource) DeepCopyInto(out *XGBoostMLPolicySource) {
	_ = "STUB: not implemented"
	return

	// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XGBoostMLPolicySource.
}

func (in *XGBoostMLPolicySource) DeepCopy() *XGBoostMLPolicySource {
	_ = "STUB: not implemented"
	return nil
}
