//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

import (
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return nil
}

func schema_pkg_apis_trainer_v1alpha1_ClusterTrainingRuntime(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_ClusterTrainingRuntimeList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_ContainerPatch(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_CoschedulingPodGroupPolicySource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_DatasetInitializer(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_FluxMLPolicySource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_Initializer(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_JAXMLPolicySource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_JobSetSpecPatch(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_JobSetTemplatePatch(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_JobSetTemplateSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_JobSpecPatch(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_JobStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_JobTemplatePatch(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_MLPolicy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_MLPolicySource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_MPIMLPolicySource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_Metric(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_ModelInitializer(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_PodGroupPolicy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_PodGroupPolicySource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_PodSpecPatch(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_PodTemplatePatch(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_ReplicatedJobPatch(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_RuntimePatch(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_RuntimeRef(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_TorchMLPolicySource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_TrainJob(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_TrainJobList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_TrainJobSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_TrainJobStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_Trainer(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_TrainerStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_TrainingRuntime(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_TrainingRuntimeList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_TrainingRuntimeSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_TrainingRuntimeSpecPatch(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_UpdateTrainJobStatusRequest(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_VolcanoPodGroupPolicySource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_trainer_v1alpha1_XGBoostMLPolicySource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_ContainerResourceMetricSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_ContainerResourceMetricStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_CrossVersionObjectReference(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_ExternalMetricSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_ExternalMetricStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_HPAScalingPolicy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_HPAScalingRules(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_HorizontalPodAutoscaler(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_HorizontalPodAutoscalerBehavior(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_HorizontalPodAutoscalerCondition(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_HorizontalPodAutoscalerList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_HorizontalPodAutoscalerSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_HorizontalPodAutoscalerStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_MetricIdentifier(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_MetricSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_MetricStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_MetricTarget(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_MetricValueStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_ObjectMetricSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_ObjectMetricStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_PodsMetricSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_PodsMetricStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_ResourceMetricSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_autoscaling_v2_ResourceMetricStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_batch_v1_CronJob(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_batch_v1_CronJobList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_batch_v1_CronJobSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_batch_v1_CronJobStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_batch_v1_Job(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_batch_v1_JobCondition(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_batch_v1_JobList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_batch_v1_JobSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_batch_v1_JobStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_batch_v1_JobTemplateSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_batch_v1_PodFailurePolicy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_batch_v1_PodFailurePolicyOnExitCodesRequirement(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_batch_v1_PodFailurePolicyOnPodConditionsPattern(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_batch_v1_PodFailurePolicyRule(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_batch_v1_SuccessPolicy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_batch_v1_SuccessPolicyRule(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_batch_v1_UncountedTerminatedPods(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_AWSElasticBlockStoreVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_Affinity(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_AppArmorProfile(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_AttachedVolume(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_AvoidPods(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_AzureDiskVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_AzureFilePersistentVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_AzureFileVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_Binding(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_CSIPersistentVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_CSIVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_Capabilities(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_CephFSPersistentVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_CephFSVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_CinderPersistentVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_CinderVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ClientIPConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ClusterTrustBundleProjection(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ComponentCondition(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ComponentStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ComponentStatusList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ConfigMap(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ConfigMapEnvSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ConfigMapKeySelector(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ConfigMapList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ConfigMapNodeConfigSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ConfigMapProjection(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ConfigMapVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_Container(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ContainerExtendedResourceRequest(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ContainerImage(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ContainerPort(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ContainerResizePolicy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ContainerRestartRule(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ContainerRestartRuleOnExitCodes(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ContainerState(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ContainerStateRunning(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ContainerStateTerminated(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ContainerStateWaiting(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ContainerStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ContainerUser(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_DaemonEndpoint(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_DownwardAPIProjection(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_DownwardAPIVolumeFile(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_DownwardAPIVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_EmptyDirVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_EndpointAddress(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_EndpointPort(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_EndpointSubset(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_Endpoints(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_EndpointsList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_EnvFromSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_EnvVar(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_EnvVarSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_EphemeralContainer(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_EphemeralContainerCommon(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_EphemeralVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_Event(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_EventList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_EventSeries(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_EventSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ExecAction(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_FCVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_FileKeySelector(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_FlexPersistentVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_FlexVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_FlockerVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_GCEPersistentDiskVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_GRPCAction(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_GitRepoVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_GlusterfsPersistentVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_GlusterfsVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_HTTPGetAction(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_HTTPHeader(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_HostAlias(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_HostIP(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_HostPathVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ISCSIPersistentVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ISCSIVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ImageVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ImageVolumeStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_KeyToPath(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_Lifecycle(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_LifecycleHandler(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_LimitRange(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_LimitRangeItem(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_LimitRangeList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_LimitRangeSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_LinuxContainerUser(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_List(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_LoadBalancerIngress(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_LoadBalancerStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_LocalObjectReference(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_LocalVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ModifyVolumeStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NFSVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_Namespace(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NamespaceCondition(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NamespaceList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NamespaceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NamespaceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_Node(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeAddress(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeAffinity(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeAllocatableResourceClaimStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeCondition(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeConfigSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeConfigStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeDaemonEndpoints(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeFeatures(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeProxyOptions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeRuntimeHandler(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeRuntimeHandlerFeatures(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeSelector(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeSelectorRequirement(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeSelectorTerm(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeSwapStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_NodeSystemInfo(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ObjectFieldSelector(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ObjectReference(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PersistentVolume(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PersistentVolumeClaim(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PersistentVolumeClaimCondition(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PersistentVolumeClaimList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PersistentVolumeClaimSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PersistentVolumeClaimStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PersistentVolumeClaimTemplate(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PersistentVolumeClaimVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PersistentVolumeList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PersistentVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PersistentVolumeSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PersistentVolumeStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PhotonPersistentDiskVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_Pod(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodAffinity(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodAffinityTerm(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodAntiAffinity(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodAttachOptions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodCertificateProjection(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodCondition(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodDNSConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodDNSConfigOption(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodExecOptions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodExtendedResourceClaimStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodIP(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodLogOptions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodOS(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodPortForwardOptions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodProxyOptions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodReadinessGate(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodResourceClaim(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodResourceClaimStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodSchedulingGate(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodSchedulingGroup(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodSecurityContext(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodSignature(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodStatusResult(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodTemplate(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodTemplateList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PodTemplateSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PortStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PortworxVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PreferAvoidPodsEntry(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_PreferredSchedulingTerm(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_Probe(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ProbeHandler(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ProjectedVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_QuobyteVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_RBDPersistentVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_RBDVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_RangeAllocation(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ReplicationController(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ReplicationControllerCondition(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ReplicationControllerList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ReplicationControllerSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ReplicationControllerStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ResourceClaim(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ResourceFieldSelector(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ResourceHealth(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ResourceQuota(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ResourceQuotaList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ResourceQuotaSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ResourceQuotaStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ResourceRequirements(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ResourceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_SELinuxOptions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ScaleIOPersistentVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ScaleIOVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ScopeSelector(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ScopedResourceSelectorRequirement(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_SeccompProfile(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_Secret(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_SecretEnvSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_SecretKeySelector(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_SecretList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_SecretProjection(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_SecretReference(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_SecretVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_SecurityContext(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_SerializedReference(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_Service(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ServiceAccount(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ServiceAccountList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ServiceAccountTokenProjection(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ServiceList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ServicePort(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ServiceProxyOptions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ServiceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_ServiceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_SessionAffinityConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_SleepAction(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_StorageOSPersistentVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_StorageOSVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_Sysctl(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_TCPSocketAction(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_Taint(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_Toleration(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_TopologySelectorLabelRequirement(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_TopologySelectorTerm(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_TopologySpreadConstraint(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_TypedLocalObjectReference(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_TypedObjectReference(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_Volume(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_VolumeDevice(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_VolumeMount(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_VolumeMountStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_VolumeNodeAffinity(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_VolumeProjection(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_VolumeResourceRequirements(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_VolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_VolumeStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_VsphereVirtualDiskVolumeSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_WeightedPodAffinityTerm(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_api_core_v1_WindowsSecurityContextOptions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_apimachinery_pkg_api_resource_Quantity(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_apimachinery_pkg_api_resource_int64Amount(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_APIGroup(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_APIGroupList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_APIResource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_APIResourceList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_APIVersions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_ApplyOptions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_Condition(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_CreateOptions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_DeleteOptions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_Duration(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_FieldSelectorRequirement(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_FieldsV1(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_GetOptions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_GroupKind(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_GroupResource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_GroupVersion(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_GroupVersionForDiscovery(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_GroupVersionKind(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_GroupVersionResource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_InternalEvent(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_LabelSelector(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_LabelSelectorRequirement(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_List(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_ListMeta(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_ListOptions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_ManagedFieldsEntry(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_MicroTime(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_ObjectMeta(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_OwnerReference(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_PartialObjectMetadata(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_PartialObjectMetadataList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_Patch(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_PatchOptions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_Preconditions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_RootPaths(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_ServerAddressByClientCIDR(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_ShardInfo(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_Status(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_StatusCause(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_StatusDetails(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_Table(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_TableColumnDefinition(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_TableOptions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_TableRow(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_TableRowCondition(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_Time(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_Timestamp(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_TypeMeta(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_UpdateOptions(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_meta_v1_WatchEvent(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_apimachinery_pkg_runtime_RawExtension(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_apimachinery_pkg_runtime_TypeMeta(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_k8sio_apimachinery_pkg_runtime_Unknown(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_apimachinery_pkg_util_intstr_IntOrString(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_jobset_api_jobset_v1alpha2_Coordinator(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_jobset_api_jobset_v1alpha2_DependsOn(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_jobset_api_jobset_v1alpha2_FailurePolicy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_jobset_api_jobset_v1alpha2_FailurePolicyRule(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_jobset_api_jobset_v1alpha2_JobSet(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_jobset_api_jobset_v1alpha2_JobSetList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_jobset_api_jobset_v1alpha2_JobSetSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_jobset_api_jobset_v1alpha2_JobSetStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_jobset_api_jobset_v1alpha2_Network(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_jobset_api_jobset_v1alpha2_ReplicatedJob(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_jobset_api_jobset_v1alpha2_ReplicatedJobStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_jobset_api_jobset_v1alpha2_StartupPolicy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_jobset_api_jobset_v1alpha2_SuccessPolicy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_jobset_api_jobset_v1alpha2_VolumeClaimPolicy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_jobset_api_jobset_v1alpha2_VolumeRetentionPolicy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_scheduling_v1beta1_Affinity(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_scheduling_v1beta1_Cluster(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_scheduling_v1beta1_Guarantee(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_scheduling_v1beta1_NetworkTopologySpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_scheduling_v1beta1_NodeGroupAffinity(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_scheduling_v1beta1_NodeGroupAntiAffinity(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_scheduling_v1beta1_PodGroup(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_scheduling_v1beta1_PodGroupCondition(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_scheduling_v1beta1_PodGroupList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_scheduling_v1beta1_PodGroupSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_scheduling_v1beta1_PodGroupStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_scheduling_v1beta1_Queue(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_scheduling_v1beta1_QueueList(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_scheduling_v1beta1_QueueSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_scheduling_v1beta1_QueueStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}

func schema_pkg_apis_scheduling_v1beta1_Reservation(ref common.ReferenceCallback) common.OpenAPIDefinition {
	_ = "STUB: not implemented"
	return *new(common.OpenAPIDefinition)
}
