// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clientset "github.com/kubeflow/trainer/v2/pkg/client/clientset/versioned"
	trainerv1alpha1 "github.com/kubeflow/trainer/v2/pkg/client/clientset/versioned/typed/trainer/v1alpha1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/discovery"
	fakediscovery "k8s.io/client-go/discovery/fake"
	"k8s.io/client-go/testing"
)

// NewSimpleClientset returns a clientset that will respond with the provided objects.
// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
// without applying any field management, validations and/or defaults. It shouldn't be considered a replacement
// for a real clientset and is mostly useful in simple unit tests.
func NewSimpleClientset(objects ...runtime.Object) *Clientset {
	_ = "STUB: not implemented"
	return nil
}

// Clientset implements clientset.Interface. Meant to be embedded into a
// struct to get a default implementation. This makes faking out just the method
// you want to test easier.
type Clientset struct {
	testing.Fake
	discovery *fakediscovery.FakeDiscovery
	tracker   testing.ObjectTracker
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	_ = "STUB: not implemented"
	return *new(discovery.DiscoveryInterface)
}

func (c *Clientset) Tracker() testing.ObjectTracker {
	_ = "STUB: not implemented"

	// IsWatchListSemanticsUnSupported informs the reflector that this client
	// doesn't support WatchList semantics.
	//
	// This is a synthetic method whose sole purpose is to satisfy the optional
	// interface check performed by the reflector.
	// Returning true signals that WatchList can NOT be used.
	// No additional logic is implemented here.
	return *new(testing.ObjectTracker)
}

func (c *Clientset) IsWatchListSemanticsUnSupported() bool {
	_ = "STUB: not implemented"

	// NewClientset returns a clientset that will respond with the provided objects.
	// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
	// without applying any validations and/or defaults. It shouldn't be considered a replacement
	// for a real clientset and is mostly useful in simple unit tests.
	//
	// Compared to NewSimpleClientset, the Clientset returned here supports field tracking and thus
	// server-side apply. Beware though that support in that for CRDs is missing
	// (https://github.com/kubernetes/kubernetes/issues/126850).
	return false
}

func NewClientset(objects ...runtime.Object) *Clientset { _ = "STUB: not implemented"; return nil }

var (
	_ clientset.Interface = &Clientset{}
	_ testing.FakeClient  = &Clientset{}
)

// TrainerV1alpha1 retrieves the TrainerV1alpha1Client
func (c *Clientset) TrainerV1alpha1() trainerv1alpha1.TrainerV1alpha1Interface {
	_ = "STUB: not implemented"
	return *new(trainerv1alpha1.TrainerV1alpha1Interface)
}
