// Copyright The Kubeflow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	http "net/http"

	trainerv1alpha1 "github.com/kubeflow/trainer/v2/pkg/client/clientset/versioned/typed/trainer/v1alpha1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	TrainerV1alpha1() trainerv1alpha1.TrainerV1alpha1Interface
}

// Clientset contains the clients for groups.
type Clientset struct {
	*discovery.DiscoveryClient
	trainerV1alpha1 *trainerv1alpha1.TrainerV1alpha1Client
}

// TrainerV1alpha1 retrieves the TrainerV1alpha1Client
func (c *Clientset) TrainerV1alpha1() trainerv1alpha1.TrainerV1alpha1Interface {
	_ = "STUB: not implemented"
	return *

	// Discovery retrieves the DiscoveryClient
	new(trainerv1alpha1.TrainerV1alpha1Interface)
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	_ = "STUB: not implemented"
	return *new(discovery.DiscoveryInterface)
}

// NewForConfig creates a new Clientset for the given config.
// If config's RateLimiter is not set and QPS and Burst are acceptable,
// NewForConfig will generate a rate-limiter in configShallowCopy.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*Clientset, error) { _ = "STUB: not implemented"; return nil, nil }

// share the transport between all clients

// NewForConfigAndClient creates a new Clientset for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
// If config's RateLimiter is not set and QPS and Burst are acceptable,
// NewForConfigAndClient will generate a rate-limiter in configShallowCopy.
func NewForConfigAndClient(c *rest.Config, httpClient *http.Client) (*Clientset, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset { _ = "STUB: not implemented"; return nil }

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset { _ = "STUB: not implemented"; return nil }
